spring:
  data:
    mongodb:
      database: WFCrud
      host: localhost
      port: 27017
  webflux:
    urlpatterns:
      - "/**"
    hiddenmethod:
      filter:
        enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    com.example: DEBUG
jwt:
  secret:
    key : 7Jqw7KO87LWc6rCVMeyhsOqwnOypjOuKlOqwnOuwnOyekOuhnOqxsOuTreuCmOyekO2ZlOydtO2MheynseynsQ==